import type { Metadata } from "next";
import { DocumentProps, Head, Html, Main, NextScript } from "next/document";
import { DocumentHeadTagsProps } from "@mui/material-nextjs/v13-pagesRouter";

export const metadata: Metadata = {
  title: "Create Turborepo",
  description: "Generated by create turbo",
};

export default function Document(
  props: DocumentProps & DocumentHeadTagsProps,
): JSX.Element {
  return (
    <Html lang="en">
      <Head></Head>
      <body>
        <Main />
        <NextScript />
      </body>
    </Html>
  );
}

// Document.getInitialProps = async (ctx: DocumentContext) => {
//   return await documentGetInitialProps(ctx);
// };
